logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate.SQL: info
    org.springframework.messaging: trace
    org.springframework.web.socket.messaging: trace
    com.dao: debug

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${/db/mysql/port:3306}/${/db/mysql/database:quiz}?verifyServerCertificate=${/db/mysql/useSSL:false}&useSSL=${/db/mysql/useSSL:false}&requireSSL=${/db/mysql/useSSL:false}

hibernate:
  connection:
    isolation: 2
  current_session_context_class: thread
  dialect: org.hibernate.dialect.MySQL8Dialect
  format_sql: true
  jdbc:
    time_zone: UTC
  max_fetch_depth: 5
  show_sql: true
  use_sql_comments: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
application:
  storage:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  messaging:
    message-broker: redis
    activemq:
      host: ${ACTIVEMQ_HOST:localhost}
      port: ${ACTIVEMQ_PORT:61613}

management:
  health:
    jms:
      enabled: false
