apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z quiz-backend 8080; do echo waiting for backend; sleep 2; done;']
      containers:
      - name: frontend
        image: quiz-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_url
        - name: WS_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: ws_url
        - name: NGINX_PORT
          value: "80"
        - name: NGINX_HOST
          value: "quiz.local"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  selector:
    app: quiz-frontend
  ports:
  - port: 80
    targetPort: 80 