{
 "title": "WebSocket Metrics",
 "tags": [ "websocket" ],
 "panels": [
  {
   "title": "Total Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(websocket_sessions_active{application=\"quiz\"})",
     "legendFormat": "Total Active Connections"
    }
   ]
  },
  {
   "title": "Connections per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "websocket_sessions_active{application=\"quiz\"}",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Total Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(websocket_messages_received_total{application=\"quiz\"}[5m]))",
     "legendFormat": "Total Messages/s"
    }
   ]
  },
  {
   "title": "Message Rate per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(websocket_messages_received_total{application=\"quiz\"}[5m])",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  }
 ]
}