apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- frontend-config.yaml
- redis.yaml
- activemq.yaml
- mysql.yaml
- nginx-deployment.yaml
- nginx-config.yaml
- prometheus-deployment.yaml
- prometheus-config.yaml
- grafana-deployment.yaml
- grafana-config.yaml
