apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-pv
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS quiz CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    GRANT ALL PRIVILEGES ON quiz.* TO 'root'@'%';
    FLUSH PRIVILEGES;

    USE quiz;
    SET NAMES utf8mb4;
    SET FOREIGN_KEY_CHECKS = 0;

    -- ----------------------------
    -- Table structure for leaderboards
    -- ----------------------------
    DROP TABLE IF EXISTS `leaderboards`;
    CREATE TABLE `leaderboards` (
        `id` int NOT NULL AUTO_INCREMENT,
        `score` int DEFAULT NULL,
        `quiz_id` int DEFAULT NULL,
        `user_id` int DEFAULT NULL,
        `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
        `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

    -- ----------------------------
    -- Table structure for quizzes
    -- ----------------------------
    DROP TABLE IF EXISTS `quizzes`;
    CREATE TABLE `quizzes` (
                               `id` int NOT NULL AUTO_INCREMENT,
                               `topic` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
                               `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
                               `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
                               PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

    -- ----------------------------
    -- Records of quizzes
    -- ----------------------------
    INSERT INTO `quizzes` (`id`, `topic`, `created_at`, `updated_at`) VALUES 
    (1, 'English', '2024-12-22 14:47:11', '2024-12-22 14:47:11'),
    (2, 'Mathematics', '2024-12-23 05:23:21', '2024-12-23 05:23:21'),
    (3, 'Physics', '2024-12-24 13:36:39', '2024-12-24 13:36:39');

    -- ----------------------------
    -- Table structure for users
    -- ----------------------------
    DROP TABLE IF EXISTS `users`;
    CREATE TABLE `users` (
        `id` int NOT NULL AUTO_INCREMENT,
        `username` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
        `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
        `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

    SET FOREIGN_KEY_CHECKS = 1;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-mysql
  template:
    metadata:
      labels:
        app: quiz-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.1.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypass123"
        - name: MYSQL_DATABASE
          value: "quiz"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-scripts
        configMap:
          name: mysql-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-mysql
spec:
  selector:
    app: quiz-mysql
  ports:
  - port: 3306
    targetPort: 3306 