apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'quiz-backend'
        metrics_path: '/api/v1/manage/prometheus'
        static_configs:
          - targets: ['quiz-backend-service:80'] 