apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-redis
  template:
    metadata:
      labels:
        app: quiz-redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.4
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-redis
spec:
  selector:
    app: quiz-redis
  ports:
  - port: 6379
    targetPort: 6379
